# Generated by Django 5.2.9 on 2026-04-11 04:40

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('ModelID', models.AutoField(primary_key=True, serialize=False)),
                ('Version', models.CharField(max_length=50)),
                ('AccuracyRate', models.FloatField()),
                ('LastTrainedDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('EntryID', models.AutoField(primary_key=True, serialize=False)),
                ('DiseaseName', models.CharField(max_length=255, unique=True)),
                ('Symptoms', models.TextField()),
                ('TreatmentInfo', models.TextField()),
                ('LastUpdated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MarketPrice',
            fields=[
                ('PriceID', models.AutoField(primary_key=True, serialize=False)),
                ('vegetable_name', models.CharField(max_length=100)),
                ('market_name', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('currency', models.CharField(default='LSL', max_length=5)),
                ('date_recorded', models.DateField(default=django.utils.timezone.now)),
                ('price_trend', models.CharField(choices=[('rising', 'Rising'), ('stable', 'Stable'), ('falling', 'Falling')], default='stable', max_length=10)),
            ],
            options={
                'ordering': ['-date_recorded'],
            },
        ),
        migrations.CreateModel(
            name='TranslationCache',
            fields=[
                ('disease_name_en', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('pesticide_st', models.CharField(max_length=255, verbose_name='Moriana (Sesotho)')),
                ('dosage_st', models.CharField(max_length=255, verbose_name='Tekanyetso (Sesotho)')),
                ('steps_st', models.TextField(verbose_name='Mekhoa ea Tšebeliso (Sesotho)')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('TreatmentID', models.AutoField(primary_key=True, serialize=False)),
                ('DiseaseName', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('RecommendedPesticide', models.CharField(max_length=255)),
                ('Dosage', models.CharField(max_length=255)),
                ('ApplicationSteps', models.TextField()),
                ('dosage_per_hectare_g', models.FloatField(blank=True, help_text='Grams or ml of product needed per hectare (e.g. 25 for 25g/ha)', null=True)),
                ('dosage_unit', models.CharField(choices=[('g', 'Grams (g)'), ('ml', 'Millilitres (ml)')], default='g', help_text="Unit for dosage_per_hectare_g — 'g' or 'ml'", max_length=5)),
                ('water_per_hectare_l', models.FloatField(blank=True, help_text='Litres of water per hectare (e.g. 200 for standard field sprayer)', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('WeatherID', models.AutoField(primary_key=True, serialize=False)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('Temperature', models.FloatField()),
                ('Humidity', models.IntegerField()),
                ('Rainfall', models.FloatField(default=0.0)),
                ('rainfall_last_7_days', models.FloatField(default=0.0)),
                ('AlertMessage', models.CharField(blank=True, max_length=255)),
                ('DateUpdated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('language_preferences', models.CharField(default='en', max_length=10)),
                ('profile_photo_url', models.CharField(blank=True, max_length=500, null=True)),
                ('farm_size_hectares', models.FloatField(blank=True, null=True)),
                ('experience_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('expert', 'Expert')], default='beginner', max_length=20)),
                ('notification_diseases', models.BooleanField(default=True)),
                ('notification_weather', models.BooleanField(default=True)),
                ('notification_market', models.BooleanField(default=False)),
                ('onboarding_complete', models.BooleanField(default=False)),
                ('last_active', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CommunityPost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('image_url', models.CharField(blank=True, max_length=500, null=True)),
                ('post_type', models.CharField(choices=[('question', 'Question'), ('tip', 'Farming Tip'), ('success', 'Success Story'), ('general', 'General')], default='general', max_length=20)),
                ('crop_type', models.CharField(blank=True, max_length=100, null=True)),
                ('likes_count', models.IntegerField(default=0)),
                ('comments_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_communitypost',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunityComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_comments', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.communitypost')),
            ],
            options={
                'db_table': 'api_communitycomment',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CropProfile',
            fields=[
                ('ProfileID', models.AutoField(primary_key=True, serialize=False)),
                ('VegetableType', models.CharField(max_length=100)),
                ('SoilEnvironment', models.CharField(blank=True, choices=[('sandy', 'Sandy'), ('clay', 'Clay'), ('loam', 'Loam'), ('silt', 'Silt'), ('sandy_loam', 'Sandy Loam'), ('clay_loam', 'Clay Loam')], max_length=20, null=True)),
                ('PlantingDate', models.DateField(blank=True, null=True)),
                ('IsActive', models.BooleanField(default=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('plot_size_hectares', models.FloatField(blank=True, null=True)),
                ('expected_harvest_date', models.DateField(blank=True, null=True)),
                ('irrigation_method', models.CharField(choices=[('rain', 'Rain-fed'), ('drip', 'Drip Irrigation'), ('flood', 'Flood Irrigation'), ('sprinkler', 'Sprinkler')], default='rain', max_length=20)),
                ('seed_variety', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('FarmerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AppAlert',
            fields=[
                ('AlertID', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=255)),
                ('Message', models.TextField()),
                ('alert_type', models.CharField(choices=[('weather', 'Weather'), ('disease', 'Disease Outbreak'), ('market', 'Market Price'), ('reminder', 'Crop Reminder'), ('system', 'System')], default='weather', max_length=50)),
                ('IsRead', models.BooleanField(default=False)),
                ('DateCreated', models.DateTimeField(auto_now_add=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High — Urgent')], default='medium', max_length=10)),
                ('district_target', models.CharField(blank=True, max_length=100, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('FarmerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL)),
                ('RelatedCrop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.cropprofile')),
            ],
        ),
        migrations.CreateModel(
            name='FarmerInsight',
            fields=[
                ('InsightID', models.AutoField(primary_key=True, serialize=False)),
                ('total_scans', models.IntegerField(default=0)),
                ('total_diseases_detected', models.IntegerField(default=0)),
                ('total_healthy_scans', models.IntegerField(default=0)),
                ('most_scanned_crop', models.CharField(blank=True, max_length=100, null=True)),
                ('most_common_disease', models.CharField(blank=True, max_length=255, null=True)),
                ('highest_risk_month', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('last_scan_date', models.DateTimeField(blank=True, null=True)),
                ('streak_healthy_days', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('FarmerID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='insight', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GrowthJournalEntry',
            fields=[
                ('EntryID', models.AutoField(primary_key=True, serialize=False)),
                ('entry_date', models.DateField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('photo_url', models.CharField(blank=True, max_length=500, null=True)),
                ('mood', models.CharField(choices=[('great', 'Great'), ('ok', 'OK'), ('concerned', 'Concerned'), ('bad', 'Bad')], default='ok', max_length=20)),
                ('DateCreated', models.DateTimeField(auto_now_add=True)),
                ('CropProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='api.cropprofile')),
                ('FarmerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-entry_date'],
            },
        ),
        migrations.CreateModel(
            name='PersonalizedRule',
            fields=[
                ('RuleID', models.AutoField(primary_key=True, serialize=False)),
                ('DiseaseName', models.CharField(max_length=255)),
                ('TriggerDistrict', models.CharField(blank=True, max_length=100, null=True)),
                ('TriggerAltitudeTier', models.CharField(choices=[('lowland', 'Lowland — below 1800m'), ('midland', 'Midland — 1800–2200m'), ('highland', 'Highland — 2200–2800m'), ('alpine', 'Alpine — above 2800m'), ('any', 'Any altitude')], default='any', max_length=10)),
                ('TriggerSoilType', models.CharField(blank=True, choices=[('sandy', 'Sandy'), ('clay', 'Clay'), ('loam', 'Loam'), ('silt', 'Silt'), ('sandy_loam', 'Sandy Loam'), ('clay_loam', 'Clay Loam')], max_length=20, null=True)),
                ('TriggerIrrigation', models.CharField(blank=True, choices=[('rain', 'Rain-fed'), ('drip', 'Drip Irrigation'), ('flood', 'Flood Irrigation'), ('sprinkler', 'Sprinkler')], max_length=20, null=True)),
                ('MinDaysSincePlanting', models.IntegerField(default=0)),
                ('MaxDaysSincePlanting', models.IntegerField(default=999)),
                ('TriggerCropVariety', models.CharField(blank=True, max_length=100, null=True)),
                ('TriggerSeason', models.CharField(choices=[('dry', 'Dry Season (May–Sep)'), ('wet', 'Wet Season (Oct–Apr)'), ('any', 'Any Season')], default='any', max_length=10)),
                ('TriggerRainfallLevel', models.CharField(choices=[('low', 'Low — < 10mm/week'), ('moderate', 'Moderate — 10–30mm/week'), ('high', 'High — > 30mm/week'), ('any', 'Any')], default='any', max_length=10)),
                ('ExpertAdvice', models.TextField()),
                ('advice_beginner', models.TextField(blank=True, null=True)),
                ('RecommendationCategory', models.CharField(default='General', max_length=50)),
                ('priority_score', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['-priority_score'],
                'indexes': [models.Index(fields=['DiseaseName', 'TriggerDistrict', 'TriggerAltitudeTier'], name='api_persona_Disease_2e7913_idx'), models.Index(fields=['DiseaseName', 'TriggerSoilType', 'TriggerIrrigation'], name='api_persona_Disease_608ce7_idx'), models.Index(fields=['DiseaseName', 'TriggerSeason', 'TriggerRainfallLevel'], name='api_persona_Disease_ea84bb_idx')],
            },
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('PlantID', models.AutoField(primary_key=True, serialize=False)),
                ('CropType', models.CharField(default='Vegetable', max_length=100)),
                ('ImageFile', models.CharField(max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('altitude_meters', models.FloatField(blank=True, null=True)),
                ('gps_district', models.CharField(blank=True, max_length=100, null=True)),
                ('DateCaptured', models.DateTimeField(auto_now_add=True)),
                ('CropProfile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.cropprofile')),
                ('FarmerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plants', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('DiagnosisID', models.AutoField(primary_key=True, serialize=False)),
                ('DiseaseName', models.CharField(max_length=255)),
                ('ConfidenceLevel', models.FloatField()),
                ('DateDiagnosed', models.DateTimeField(auto_now_add=True)),
                ('farmer_feedback', models.CharField(blank=True, choices=[('correct', 'Correct'), ('incorrect', 'Incorrect'), ('unsure', 'Not Sure')], max_length=20, null=True)),
                ('severity', models.CharField(blank=True, choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')], max_length=20, null=True)),
                ('treatment_applied', models.BooleanField(default=False)),
                ('treatment_outcome', models.CharField(blank=True, choices=[('recovered', 'Recovered'), ('no_change', 'No Change'), ('worsened', 'Worsened')], max_length=20, null=True)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('PlantID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='api.plant')),
            ],
        ),
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_likes', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='api.communitypost')),
            ],
            options={
                'db_table': 'api_postlike',
            },
        ),
        migrations.AddIndex(
            model_name='communitypost',
            index=models.Index(fields=['-created_at'], name='api_communi_created_d9f1f6_idx'),
        ),
        migrations.AddIndex(
            model_name='communitypost',
            index=models.Index(fields=['farmer', '-created_at'], name='api_communi_farmer__b569d2_idx'),
        ),
        migrations.AddIndex(
            model_name='communitypost',
            index=models.Index(fields=['crop_type'], name='api_communi_crop_ty_8f23bc_idx'),
        ),
        migrations.AddIndex(
            model_name='communitypost',
            index=models.Index(fields=['post_type'], name='api_communi_post_ty_4d30a9_idx'),
        ),
        migrations.AddIndex(
            model_name='communitycomment',
            index=models.Index(fields=['post', 'created_at'], name='api_communi_post_id_a2d8cb_idx'),
        ),
        migrations.AddIndex(
            model_name='communitycomment',
            index=models.Index(fields=['farmer'], name='api_communi_farmer__438c4f_idx'),
        ),
        migrations.AddIndex(
            model_name='postlike',
            index=models.Index(fields=['post', 'farmer'], name='api_postlik_post_id_71ca4d_idx'),
        ),
        migrations.AddIndex(
            model_name='postlike',
            index=models.Index(fields=['farmer'], name='api_postlik_farmer__f9736c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='postlike',
            unique_together={('post', 'farmer')},
        ),
    ]
