# Generated by Django 5.2.9 on 2026-01-12 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('ModelID', models.AutoField(primary_key=True, serialize=False)),
                ('Version', models.CharField(max_length=50)),
                ('AccuracyRate', models.FloatField()),
                ('LastTrainedDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('DiagnosisID', models.AutoField(primary_key=True, serialize=False)),
                ('DiseaseName', models.CharField(max_length=255)),
                ('ConfidenceLevel', models.FloatField()),
                ('DateDiagnosed', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('EntryID', models.AutoField(primary_key=True, serialize=False)),
                ('DiseaseName', models.CharField(max_length=255)),
                ('Symptoms', models.TextField()),
                ('TreatmentInfo', models.TextField()),
                ('LastUpdated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('TreatmentID', models.AutoField(primary_key=True, serialize=False)),
                ('RecommendedPesticide', models.CharField(max_length=255)),
                ('Dosage', models.CharField(max_length=255)),
                ('ApplicationSteps', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='CropDisease',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='language_preference',
        ),
        migrations.AddField(
            model_name='farmer',
            name='language_preferences',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='Farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='treatment',
            name='Diagnosis',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.diagnosis'),
        ),
    ]
