# Generated by Django 5.2.9 on 2026-04-27 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='recommendation_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='Causes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='dosage_per_hectare_g',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='dosage_unit',
            field=models.CharField(choices=[('g', 'Grams (g)'), ('ml', 'Millilitres (ml)')], default='g', max_length=5),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='water_per_hectare_l',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
