# Generated by Django 5.1.6 on 2026-05-10 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_diagnosis_recommendation_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='translationcache',
            name='causes_st',
            field=models.TextField(blank=True, null=True, verbose_name='Lisosa (Sesotho)'),
        ),
    ]
