# Generated by Django 5.2.9 on 2026-01-14 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_aimodel_diagnosis_knowledgebase_treatment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('WeatherID', models.AutoField(primary_key=True, serialize=False)),
                ('Temperature', models.FloatField()),
                ('Humidity', models.IntegerField()),
                ('DateUpdated', models.DateTimeField(auto_now=True)),
                ('Rainfall', models.FloatField(default=0.0)),
                ('AlertMessage', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='diagnosis',
            name='Farmer',
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('PlantID', models.AutoField(primary_key=True, serialize=False)),
                ('CropType', models.CharField(max_length=100)),
                ('ImageFile', models.CharField(max_length=255)),
                ('DateCaptured', models.DateTimeField(auto_now_add=True)),
                ('FarmerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plants', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='PlantID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='api.plant'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('ReportID', models.AutoField(primary_key=True, serialize=False)),
                ('DiagnosisSummary', models.TextField()),
                ('TreatmentSummary', models.TextField()),
                ('ReportDate', models.DateTimeField(auto_now_add=True)),
                ('FarmerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
