# Generated by Django 5.2.9 on 2026-01-18 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_weatherdata_remove_diagnosis_farmer_plant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='DiseaseName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='DiseaseName',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='Diagnosis',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.diagnosis'),
        ),
    ]
