# Generated by Django 5.2.9 on 2026-01-24 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_treatment_diseasename_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropProfile',
            fields=[
                ('ProfileID', models.AutoField(primary_key=True, serialize=False)),
                ('VegetableType', models.CharField(max_length=100)),
                ('SoilEnvironment', models.CharField(blank=True, max_length=100, null=True)),
                ('FarmLocation', models.CharField(blank=True, max_length=255, null=True)),
                ('PlantingDate', models.DateField(blank=True, null=True)),
                ('IsActive', models.BooleanField(default=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('FarmerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AppAlert',
            fields=[
                ('AlertID', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=255)),
                ('Message', models.TextField()),
                ('IsRead', models.BooleanField(default=False)),
                ('DateCreated', models.DateTimeField(auto_now_add=True)),
                ('FarmerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL)),
                ('RelatedCrop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.cropprofile')),
            ],
        ),
        migrations.AddField(
            model_name='plant',
            name='CropProfile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.cropprofile'),
        ),
    ]
