# Generated by Django 5.2.9 on 2026-01-25 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_cropprofile_appalert_plant_cropprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='appalert',
            name='alert_type',
            field=models.CharField(default='weather', max_length=50),
        ),
    ]
