# Generated by Django 5.2.9 on 2026-01-26 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_appalert_alert_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalizedRule',
            fields=[
                ('RuleID', models.AutoField(primary_key=True, serialize=False)),
                ('DiseaseName', models.CharField(max_length=255)),
                ('TriggerSoilType', models.CharField(blank=True, max_length=100, null=True)),
                ('TriggerLocation', models.CharField(blank=True, max_length=100, null=True)),
                ('ExpertAdvice', models.TextField()),
            ],
        ),
    ]
