# Generated by Django 5.2.9 on 2026-01-26 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_personalizedrule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatment',
            name='Diagnosis',
        ),
        migrations.AlterField(
            model_name='plant',
            name='CropType',
            field=models.CharField(default='Vegetable', max_length=100),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='DiseaseName',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
