# Generated by Django 5.2.9 on 2026-01-28 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_treatment_diagnosis_alter_plant_croptype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalizedrule',
            name='MaxDaysSincePlanting',
            field=models.IntegerField(default=999),
        ),
        migrations.AddField(
            model_name='personalizedrule',
            name='MinDaysSincePlanting',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='personalizedrule',
            name='RecommendationCategory',
            field=models.CharField(default='General', help_text='e.g., Irrigation, Nutrition', max_length=50),
        ),
        migrations.AlterField(
            model_name='personalizedrule',
            name='TriggerLocation',
            field=models.CharField(blank=True, help_text='e.g., Maseru, Leribe', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personalizedrule',
            name='TriggerSoilType',
            field=models.CharField(blank=True, help_text='e.g., Sandy, Clayey', max_length=100, null=True),
        ),
    ]
