# Generated by Django 5.2.9 on 2026-02-12 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_personalizedrule_maxdayssinceplanting_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationCache',
            fields=[
                ('text_hash', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('english_text', models.TextField()),
                ('sesotho_text', models.TextField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
